export const GITHUB_CONFIG = {
  branch: "main",
  repo: "ossperks",
  user: "Aniket-508",
};

export const LINK = {
  AGENTCN: "https://agentcn.run",
  AWESOME_LIST_STARTER: "https://github.com/Aniket-508/awesome-list-starter",
  CLI: `https://github.com/${GITHUB_CONFIG.user}/${GITHUB_CONFIG.repo}/blob/${GITHUB_CONFIG.branch}/packages/docs/content/cli`,
  EDITORCN: "https://editorcn.vercel.app",
  EMAILCN: "https://emailcn.run",
  FOLLOWERS_VIDEO: "https://followers.video",
  FRAMECN: "https://framecn.dev",
  GITHUB: `https://github.com/${GITHUB_CONFIG.user}/${GITHUB_CONFIG.repo}`,
  HEROICONS_ANIMATED: "https://www.heroicons-animated.com",
  LICENSE: `https://github.com/${GITHUB_CONFIG.user}/${GITHUB_CONFIG.repo}/blob/${GITHUB_CONFIG.branch}/LICENSE`,
  LINGO: "https://lingo.dev",
  MCPCN: "https://mcpcn.dev",
  OGIMAGECN: "https://ogimagecn.com",
  PDFCN: "https://pdfcn.dev",
  PORTFOLIO: "https://aniketpawar.com",
  SHADCN_CSSINJS: "https://shadcn-cssinjs.com",
  SHADCN_LABS: "https://www.shadcn-labs.com",
  SHADERCN: "https://shadercn.run",
  SPONSOR: `https://github.com/sponsors/${GITHUB_CONFIG.user}`,
  STARTERCN: "https://startercn.vercel.app",
  TERMCN: "https://www.termcn.dev",
  TWITTER: "https://x.com/alaymanguy",
  VERCEL: "https://vercel.com",
  VERCEL_DOCTOR: "https://vercel-doctor.com",
} as const;
